### ISSUE TITLE
Установка компонента не в режиме Supervisor 

### ISSUE THREAD

**Issue by SeitHali** [alexmorbo/domru#5]
Здравствуйте. Подскажите как установить компонент на HA который просто в докере крутится

**Comment by alexmorbo** [comment]
Примерно как-то так.
Образ для малины - domru-armv7:0.1.1
Образ для Intel Nuc / etc - domru-amd64:0.1.1

```
docker run -d --name=domru -p 10080:80 /путь/к/папке/share/у/home/assistant:/share alexmorbo/domru-armv7:0.1.1
```

или через docker-compose.yml  
```
  domru:
    container_name: lib_domru
    image: alexmorbo/domru-armv7:0.1.1
    restart: always
    ports:
      - 10080:80
    volumes:
      - /путь/к/папке/share/у/home/assistant:/share
```


Далее заходить на ip-с-home-assustant:10080
